/**
 * Hosting rules generated from the redirect map, for whichever host serves the static build:
 * `_redirects` + `_headers` (Netlify, Cloudflare Pages), `.htaccess` (Apache), `web.config` (IIS)
 * and `nginx.conf` (included from a server block). All carry the same 301/410 rules, the 404 page,
 * security headers and long-lived caching for content-hashed files.
 */
import type { Redirect } from '../../schema/content.ts';

export const GENERATED_NOTE =
  'Generated by tools/postbuild from the content snapshot (redirects.json). Do not edit; rebuild instead.';

/** Safe for any page of this site: no framing by others, no plugins, no powerful features. */
export const SECURITY_HEADERS: readonly (readonly [string, string])[] = [
  ['X-Content-Type-Options', 'nosniff'],
  ['Referrer-Policy', 'strict-origin-when-cross-origin'],
  ['Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()'],
  ['Cross-Origin-Opener-Policy', 'same-origin'],
  ['Content-Security-Policy', "frame-ancestors 'self'; base-uri 'self'; object-src 'none'"],
];

export const IMMUTABLE = 'public, max-age=31536000, immutable';
export const REVALIDATE = 'public, max-age=0, must-revalidate';

/** Angular's content-hashed bundles at the web root, e.g. `main-T2A73JZ3.js`, `chunk-6ib5-Fja.js`. */
export const HASHED_BUNDLE = /^(?:main|chunk|styles|polyfills)-[A-Za-z0-9_-]{8,}\.(?:js|css)$/;
const HASHED_BUNDLE_SOURCE = '(?:main|chunk|styles|polyfills)-[A-Za-z0-9_-]{8,}\\.(?:js|css)';

/** Directories whose file names change whenever their content does. */
export const IMMUTABLE_DIRS = ['media', 'fonts'] as const;

export interface HostingInput {
  /** Old paths decoded, targets percent-encoded (as the sync writes them). */
  redirects: Redirect[];
  /** Hashed bundle file names found in the build (for hosts without pattern matching). */
  bundles: string[];
}

interface PathRule {
  /** Paths to match (the old URL, plus its form without the trailing slash). */
  paths: string[];
  status: 301 | 410;
  to: string;
}

interface QueryRule {
  /** Old WordPress short link parameter, e.g. `page_id=12` on `/` or `/index.php`. */
  param: string;
  value: string;
  to: string;
}

function rules(redirects: Redirect[]): { paths: PathRule[]; queries: QueryRule[] } {
  const paths: PathRule[] = [];
  const queries: QueryRule[] = [];
  for (const redirect of redirects) {
    const url = new URL(redirect.from, 'http://x');
    if (url.search) {
      const entries = [...url.searchParams];
      const [param = '', value = ''] = entries[0] ?? [];
      // Short links live on the front controller; anything else has no stable meaning on a static host.
      if (
        entries.length === 1 &&
        /^[a-z_]+$/.test(param) &&
        /^[\w-]+$/.test(value) &&
        ['/', '/index.php'].includes(url.pathname)
      ) {
        queries.push({ param, value, to: redirect.to });
      }
      continue;
    }
    const from = redirect.from;
    const variants = from.length > 1 && from.endsWith('/') ? [from, from.slice(0, -1)] : [from];
    paths.push({ paths: variants, status: redirect.status, to: redirect.to });
  }
  // A path listed twice keeps its first rule (the map is sorted, so this is deterministic).
  const seen = new Set<string>();
  for (const rule of paths) {
    rule.paths = rule.paths.filter((p) => !seen.has(p) && seen.add(p));
  }
  return { paths: paths.filter((rule) => rule.paths.length), queries };
}

/**
 * The request path as sent on the wire (percent-encoded), and as decoded when that differs and has no
 * whitespace (the file format is whitespace-separated).
 */
function wireForms(path: string): string[] {
  const encoded = encodeURI(path);
  return encoded === path || /\s/.test(path) ? [encoded] : [encoded, path];
}

const regexEscape = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Anchored regex for a path, without the leading slash (Apache and IIS match that form). */
function pathPattern(path: string): string {
  return `^${regexEscape(path.replace(/^\//, ''))}$`;
}

/**
 * mod_rewrite reads its arguments raw (no quote unescaping), so patterns go unquoted with `\\ ` for
 * spaces, and substitutions escape `%` / `$` (with NE, so percent-encoded targets aren't encoded twice).
 */
function rewriteTarget(to: string): { target: string; flags: string } {
  return to.includes('%')
    ? { target: to.replace(/[%$]/g, '\\$&'), flags: ',NE' }
    : { target: to.replace(/\$/g, '\\$'), flags: '' };
}

/** One exact pattern per old path (both slash forms are already listed by `rules`). */
function patternRules(input: HostingInput): { pattern: string; rule: PathRule }[] {
  return rules(input.redirects).paths.flatMap((rule) =>
    rule.paths.map((path) => ({ pattern: pathPattern(path), rule })),
  );
}

export function netlifyRedirects(input: HostingInput): string {
  const lines = [
    `# ${GENERATED_NOTE}`,
    '# Netlify and Cloudflare Pages. Portable rules only: query-string short links (/?page_id=, /?p=)',
    '# show the home page (canonical /) and retired WordPress endpoints get the 404 page instead of 410.',
    '# .htaccess, web.config and nginx.conf handle both.',
  ];
  for (const rule of rules(input.redirects).paths) {
    if (rule.status !== 301) continue;
    for (const path of rule.paths.flatMap(wireForms)) lines.push(`${path} ${rule.to} 301`);
  }
  return `${lines.join('\n')}\n`;
}

/** Cloudflare Pages allows at most 100 header rules; beyond that, fall back to splat patterns. */
const MAX_HEADER_RULES = 100;

export function netlifyHeaders(input: HostingInput): string {
  const block = (path: string, headers: readonly (readonly [string, string])[]) =>
    [path, ...headers.map(([name, value]) => `  ${name}: ${value}`)].join('\n');
  const cache = (path: string) => block(path, [['Cache-Control', IMMUTABLE]]);
  const fixed = [block('/*', SECURITY_HEADERS), ...IMMUTABLE_DIRS.map((dir) => cache(`/${dir}/*`))];
  const bundles =
    fixed.length + input.bundles.length <= MAX_HEADER_RULES
      ? [...input.bundles].sort().map((file) => cache(`/${file}`))
      : ['main', 'chunk', 'styles', 'polyfills'].map((name) => cache(`/${name}-*`));
  return `# ${GENERATED_NOTE}\n${[...fixed, ...bundles].join('\n\n')}\n`;
}

export function htaccess(input: HostingInput): string {
  const { queries } = rules(input.redirects);
  const quote = (text: string) => `"${text}"`;
  const lines = [
    `# ${GENERATED_NOTE}`,
    '<IfModule mod_autoindex.c>',
    '  Options -Indexes',
    '</IfModule>',
    '<IfModule mod_negotiation.c>',
    '  Options -MultiViews',
    '</IfModule>',
    '<IfModule mod_dir.c>',
    '  DirectoryIndex index.html',
    '  DirectorySlash On',
    '</IfModule>',
    'ErrorDocument 404 /404.html',
    'ErrorDocument 410 /404.html',
    '',
    '<IfModule mod_mime.c>',
    '  AddType application/manifest+json .webmanifest',
    '  AddType image/avif .avif',
    '  AddType image/webp .webp',
    '  AddType font/woff2 .woff2',
    '</IfModule>',
    '',
    '<IfModule mod_rewrite.c>',
    '  RewriteEngine On',
  ];
  if (queries.length) lines.push('', '  # WordPress short links');
  for (const query of queries) {
    const { target, flags } = rewriteTarget(query.to);
    lines.push(
      `  RewriteCond %{QUERY_STRING} (?:^|&)${regexEscape(query.param)}=${regexEscape(query.value)}(?:&|$)`,
      `  RewriteRule ^(?:index\\.php)?$ ${target} [R=301,L,QSD${flags}]`,
    );
  }
  const patterns = patternRules(input);
  if (patterns.length) lines.push('', '  # Old URLs and retired WordPress endpoints');
  for (const { pattern, rule } of patterns) {
    const unquoted = pattern.replace(/ /g, '\\ ');
    const { target, flags } = rewriteTarget(rule.to);
    lines.push(
      rule.status === 301
        ? `  RewriteRule ${unquoted} ${target} [R=301,L${flags}]`
        : `  RewriteRule ${unquoted} - [G,L]`,
    );
  }
  lines.push(
    '</IfModule>',
    '',
    '<IfModule mod_headers.c>',
    ...SECURITY_HEADERS.map(([name, value]) => `  Header always set ${name} ${quote(value)}`),
    `  Header set Cache-Control ${quote(REVALIDATE)} "expr=%{CONTENT_TYPE} =~ m#^text/html#"`,
    `  <If "%{REQUEST_URI} =~ m#^/(?:${IMMUTABLE_DIRS.join('|')})/# || %{REQUEST_URI} =~ m#^/${HASHED_BUNDLE_SOURCE}$#">`,
    `    Header set Cache-Control ${quote(IMMUTABLE)}`,
    '  </If>',
    '</IfModule>',
    '',
  );
  return lines.join('\n');
}

function xmlAttr(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function webConfig(input: HostingInput): string {
  const { queries } = rules(input.redirects);
  const redirect = (to: string) =>
    `<action type="Redirect" url="${xmlAttr(to)}" redirectType="Permanent" appendQueryString="false" />`;
  const rewrite: string[] = [];
  queries.forEach((query, i) => {
    rewrite.push(
      `        <rule name="short-link-${i + 1}" stopProcessing="true">`,
      '          <match url="^(?:index\\.php)?$" />',
      '          <conditions>',
      `            <add input="{QUERY_STRING}" pattern="${xmlAttr(`(?:^|&)${regexEscape(query.param)}=${regexEscape(query.value)}(?:&|$)`)}" />`,
      '          </conditions>',
      `          ${redirect(query.to)}`,
      '        </rule>',
    );
  });
  patternRules(input).forEach(({ pattern, rule }, i) => {
    rewrite.push(
      `        <rule name="${rule.status === 301 ? 'redirect' : 'gone'}-${i + 1}" stopProcessing="true">`,
      `          <match url="${xmlAttr(pattern)}" />`,
      rule.status === 301
        ? `          ${redirect(rule.to)}`
        : '          <action type="CustomResponse" statusCode="410" statusReason="Gone" statusDescription="This page was retired." />',
      '        </rule>',
    );
  });
  const immutable = `^/(?:${IMMUTABLE_DIRS.join('|')})/|^/${HASHED_BUNDLE_SOURCE}$`;
  const mime = [
    ['.webmanifest', 'application/manifest+json'],
    ['.avif', 'image/avif'],
    ['.webp', 'image/webp'],
    ['.woff2', 'font/woff2'],
  ];
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<!-- ${GENERATED_NOTE} IIS with the URL Rewrite module. -->`,
    '<configuration>',
    '  <system.webServer>',
    '    <defaultDocument enabled="true">',
    '      <files>',
    '        <clear />',
    '        <add value="index.html" />',
    '      </files>',
    '    </defaultDocument>',
    '    <directoryBrowse enabled="false" />',
    '    <staticContent>',
    ...mime.flatMap(([ext, type]) => [
      `      <remove fileExtension="${ext}" />`,
      `      <mimeMap fileExtension="${ext}" mimeType="${type}" />`,
    ]),
    '    </staticContent>',
    '    <httpErrors errorMode="Custom" existingResponse="Replace">',
    ...['404', '410'].flatMap((code) => [
      `      <remove statusCode="${code}" />`,
      `      <error statusCode="${code}" path="/404.html" responseMode="ExecuteURL" />`,
    ]),
    '    </httpErrors>',
    '    <httpProtocol>',
    '      <customHeaders>',
    '        <remove name="X-Powered-By" />',
    ...SECURITY_HEADERS.map(
      ([name, value]) => `        <add name="${name}" value="${xmlAttr(value)}" />`,
    ),
    '      </customHeaders>',
    '    </httpProtocol>',
    '    <rewrite>',
    '      <rules>',
    ...rewrite,
    '      </rules>',
    '      <outboundRules>',
    '        <rule name="immutable-assets" preCondition="immutable">',
    '          <match serverVariable="RESPONSE_Cache_Control" pattern=".*" />',
    `          <action type="Rewrite" value="${IMMUTABLE}" />`,
    '        </rule>',
    '        <preConditions>',
    '          <preCondition name="immutable">',
    '            <add input="{RESPONSE_STATUS}" pattern="^200$" />',
    `            <add input="{REQUEST_URI}" pattern="${xmlAttr(immutable)}" />`,
    '          </preCondition>',
    '        </preConditions>',
    '      </outboundRules>',
    '    </rewrite>',
    '  </system.webServer>',
    '</configuration>',
    '',
  ].join('\n');
}

export function nginxConf(input: HostingInput): string {
  const { paths, queries } = rules(input.redirects);
  const quote = (text: string) => {
    // nginx strings can't escape `$` (variables) or quotes; slugs and header values never contain them.
    if (/["\\$]/.test(text)) throw new Error(`nginx.conf: unsupported characters in ${text}`);
    return `"${text}"`;
  };
  const security = SECURITY_HEADERS.map(
    ([name, value]) => `add_header ${name} ${quote(value)} always;`,
  );
  // add_header in a location replaces the server-level ones, so each location repeats them.
  const withHeaders = (lines: string[]) => [...lines, ...security].map((line) => `  ${line}`);
  const shortLinks = queries.map(
    (query) =>
      `  if ($arg_${query.param} = ${quote(query.value)}) { return 301 ${quote(query.to)}; }`,
  );
  const lines = [
    `# ${GENERATED_NOTE}`,
    '#',
    '# Include inside the server {} block for the site, with root pointing at the build output:',
    '#   root /srv/compass-portal/browser;',
    '#   include /srv/compass-portal/deploy/nginx.conf;',
    '',
    'index index.html;',
    'absolute_redirect off;',
    'server_tokens off;',
    'error_page 404 /404.html;',
    'error_page 410 /404.html;',
    'charset utf-8;',
    'gzip on;',
    'gzip_types text/css text/javascript application/javascript image/svg+xml application/manifest+json application/xml text/plain;',
    ...security,
    `add_header Cache-Control ${quote(REVALIDATE)};`,
    '',
    '# Directories redirect to their trailing-slash URL (nginx does this by default), then serve index.html.',
    'location / {',
    '}',
    '',
    'location = /404.html {',
    '  internal;',
    '}',
  ];
  if (queries.length) {
    lines.push('', '# WordPress short links');
    for (const path of ['/', '/index.php']) {
      const tail = path === '/' ? [] : ['  return 301 /;'];
      lines.push(`location = ${path} {`, ...shortLinks, ...tail, '}');
    }
  }
  const exact = paths.flatMap((rule) =>
    rule.paths
      .filter((path) => !(queries.length && ['/', '/index.php'].includes(path)))
      .map((path) =>
        rule.status === 301
          ? `location = ${quote(path)} { return 301 ${quote(rule.to)}; }`
          : `location = ${quote(path)} { return 410; }`,
      ),
  );
  if (exact.length) lines.push('', '# Old URLs and retired WordPress endpoints', ...exact);
  lines.push(
    '',
    '# Content-hashed files never change: cache them for a year.',
    ...IMMUTABLE_DIRS.flatMap((dir) => [
      `location ^~ /${dir}/ {`,
      ...withHeaders([`add_header Cache-Control ${quote(IMMUTABLE)};`]),
      '}',
    ]),
    `location ~ "^/${HASHED_BUNDLE_SOURCE}$" {`,
    ...withHeaders([`add_header Cache-Control ${quote(IMMUTABLE)};`]),
    '}',
    '',
    'location = /manifest.webmanifest {',
    '  types { }',
    '  default_type application/manifest+json;',
    ...withHeaders([]),
    '}',
    '',
  );
  return lines.join('\n');
}
