/**
 * Generates src/styles/fonts.css: self-hosted @font-face rules (files copied to /fonts by angular.json)
 * plus metric-matched fallback faces, so text keeps its size and line breaks while the web fonts load.
 *
 *   node tools/design/fonts.ts
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import georgia from '@capsizecss/metrics/georgia';
import hankenGrotesk from '@capsizecss/metrics/hankenGrotesk';
import sourceSerif4 from '@capsizecss/metrics/sourceSerif4';
import { ROOT } from '../content-sync/config.ts';

const LATIN =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';
const LATIN_EXT =
  'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF';

interface Face {
  family: string;
  file: string;
  weight: string;
  style: 'normal' | 'italic';
}

const faces: Face[] = [];
for (const style of ['normal', 'italic'] as const) {
  for (const subset of ['latin', 'latin-ext']) {
    faces.push(
      {
        family: 'Source Serif 4',
        file: `source-serif-4-${subset}-wght-${style}.woff2`,
        weight: '200 900',
        style,
      },
      {
        family: 'Hanken Grotesk',
        file: `hanken-grotesk-${subset}-wght-${style}.woff2`,
        weight: '100 900',
        style,
      },
    );
  }
}

const faceCss = faces
  .map(
    (face) => `@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url('/fonts/${face.file}') format('woff2');
  unicode-range: ${face.file.includes('latin-ext') ? LATIN_EXT : LATIN};
}`,
  )
  .join('\n\n');

const serif = createFontStack([sourceSerif4, georgia], {
  fontFaceFormat: 'styleString',
});
const sans = createFontStack([hankenGrotesk, arial], {
  fontFaceFormat: 'styleString',
});

const css = `/* Generated by tools/design/fonts.ts. Do not edit by hand. */

${faceCss}

/* Metric-matched fallbacks (Capsize): the page doesn't shift when the web fonts swap in. */
${serif.fontFaces}

${sans.fontFaces}

:root {
  --font-stack-serif: ${serif.fontFamily}, serif;
  --font-stack-sans: ${sans.fontFamily}, system-ui, sans-serif;
}
`;

const target = path.join(ROOT, 'src/styles/fonts.css');
await writeFile(target, css);
console.error(`[design] Wrote ${path.relative(ROOT, target)}`);
