/**
 * Generates the font block in src/index.html: self-hosted @font-face rules (files copied to /fonts by angular.json)
 * plus metric-matched fallback faces, so text keeps its size and line breaks while the web fonts load.
 *
 *   node tools/design/fonts.ts
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import georgia from '@capsizecss/metrics/georgia';
import notoSerif from '@capsizecss/metrics/notoSerif';
import roboto from '@capsizecss/metrics/roboto';
import timesNewRoman from '@capsizecss/metrics/timesNewRoman';
import hankenGrotesk from '@capsizecss/metrics/hankenGrotesk';
import sourceSerif4 from '@capsizecss/metrics/sourceSerif4';
import { ROOT } from '../content-sync/config.ts';

const LATIN =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';
const LATIN_EXT =
  'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF';

interface Face {
  family: string;
  file: string;
  weight: string;
  style: 'normal' | 'italic';
  /** Defaults to the file's Latin or Latin Extended subset. */
  unicodeRange?: string;
}

/** fontsource's `arabic` subset (only Arabic text downloads these files). */
const ARABIC =
  'U+0600-06FF, U+0750-077F, U+0870-088E, U+0890-0891, U+0897-08E1, U+08E3-08FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE70-FE74, U+FE76-FEFC';

const faces: Face[] = [];
for (const style of ['normal', 'italic'] as const) {
  for (const subset of ['latin', 'latin-ext']) {
    faces.push(
      {
        family: 'Source Serif 4',
        file: `source-serif-4-${subset}-wght-${style}.woff2`,
        weight: '200 900',
        style,
      },
      {
        family: 'Hanken Grotesk',
        file: `hanken-grotesk-${subset}-wght-${style}.woff2`,
        weight: '100 900',
        style,
      },
    );
  }
}
// Arabic pages: Noto Naskh Arabic, a book naskh, for display (beside the serif), and Noto Sans
// Arabic for text (beside the grotesque). Arabic has no italic; browsers keep the upright face.
faces.push(
  {
    family: 'Noto Naskh Arabic',
    // Cut to the site's Arabic letters by tools/media/build.ts.
    file: 'noto-naskh-arabic-site.woff2',
    weight: '400 700',
    style: 'normal',
    unicodeRange: ARABIC,
  },
  {
    family: 'Noto Sans Arabic',
    file: 'noto-sans-arabic-site.woff2',
    weight: '100 900',
    style: 'normal',
    unicodeRange: ARABIC,
  },
);

const faceCss = faces
  .map(
    (face) => `@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url('/fonts/${face.file}') format('woff2');
  unicode-range: ${face.unicodeRange ?? (face.file.includes('latin-ext') ? LATIN_EXT : LATIN)};
}`,
  )
  .join('\n\n');

/*
 * One matched fallback per platform font, so the page doesn't shift wherever the web fonts arrive
 * late: Georgia and Arial (Windows, macOS), Noto Serif and Roboto (Android), and the Times New
 * Roman / Arial metric clones Liberation Serif and Liberation Sans (Linux, including CI).
 */
const serif = createFontStack([sourceSerif4, georgia, notoSerif, timesNewRoman], {
  fontFaceFormat: 'styleString',
});
const sans = createFontStack([hankenGrotesk, arial, roboto], {
  fontFaceFormat: 'styleString',
});
const clones: Record<string, string> = {
  "local('Times New Roman')": "local('Times New Roman'), local('Liberation Serif')",
  "local('Arial')": "local('Arial'), local('Liberation Sans')",
};
const withClones = (faces: string) =>
  Object.entries(clones).reduce((css, [from, to]) => css.split(from).join(to), faces);

/** The Arabic face right after the Latin one: the browser takes Arabic glyphs from it. */
const withArabic = (stack: string, arabic: string) =>
  stack.replace(/^([^,]+),/, `$1, '${arabic}',`);

const css = `${faceCss}

/* Metric-matched fallbacks (Capsize): the page doesn't shift when the web fonts swap in. */
${withClones(serif.fontFaces)}

${withClones(sans.fontFaces)}

:root {
  --font-stack-serif: ${withArabic(serif.fontFamily, 'Noto Naskh Arabic')}, serif;
  --font-stack-sans: ${withArabic(sans.fontFamily, 'Noto Sans Arabic')}, system-ui, sans-serif;
}
`;

// Inlined into index.html, not bundled with the stylesheet: the critical-CSS step (beasties)
// leaves @font-face rules out of the inlined CSS, so until the full stylesheet arrived the first
// paint had neither the web fonts nor the matched fallbacks, and the hero headline rewrapped.
const target = path.join(ROOT, 'src/index.html');
const START = '<!-- fonts:start (generated by tools/design/fonts.ts) -->';
const END = '<!-- fonts:end -->';
const html = await readFile(target, 'utf8');
const from = html.indexOf(START);
const to = html.indexOf(END);
if (from === -1 || to === -1) throw new Error(`${target} has no ${START} … ${END} block`);
await writeFile(
  target,
  `${html.slice(0, from + START.length)}\n<style>\n${css}</style>\n${html.slice(to)}`,
);
console.error(`[design] Wrote the font faces into ${path.relative(ROOT, target)}`);
