/**
 * Copies the few brand marks the site links to from simple-icons (CC0) into a small committed file,
 * so the app never bundles the whole icon set.
 *
 *   node tools/design/icons.ts
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import * as icons from 'simple-icons';
import { ROOT } from '../content-sync/config.ts';

const BRANDS: Record<string, keyof typeof icons> = {
  facebook: 'siFacebook',
  x: 'siX',
  instagram: 'siInstagram',
  youtube: 'siYoutube',
  whatsapp: 'siWhatsapp',
  tiktok: 'siTiktok',
  snapchat: 'siSnapchat',
  'google-play': 'siGoogleplay',
  'app-store': 'siAppstore',
};

const lines = [
  '// Generated by tools/design/icons.ts from simple-icons (CC0-1.0). Do not edit.',
  'export const BRAND_PATHS = {',
];
for (const [name, key] of Object.entries(BRANDS)) {
  const icon = icons[key] as { path: string };
  lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(icon.path)},`);
}
lines.push('} as const;', '');

const target = path.join(ROOT, 'src/app/layout/icon/brand-paths.ts');
await writeFile(target, lines.join('\n'));
console.error(`[design] Wrote ${path.relative(ROOT, target)}`);
