/**
 * Generates src/styles/easing.css with `--ease-settle`: a CSS `linear()` easing sampled from a damped
 * spring, used for the compass needle swinging past north and settling. Deterministic output.
 *
 *   node tools/design/spring.ts
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ROOT } from '../content-sync/config.ts';

export interface SpringOptions {
  /** Damping ratio: < 1 overshoots. A compass needle swings a few times before settling. */
  damping: number;
  /** Residual amplitude at t = 1 (how settled the needle is when the animation ends). */
  settleTolerance: number;
  samples: number;
  /** Max deviation (in progress units) allowed when dropping points. */
  simplifyTolerance: number;
}

/** Position of an underdamped spring released from 0 towards 1, over normalized time t ∈ [0, 1]. */
export function springCurve(options: SpringOptions): [number, number][] {
  const { damping: zeta, settleTolerance, samples } = options;
  // Choose the natural frequency so the envelope e^(-ζωt) reaches the tolerance at t = 1.
  const omega = -Math.log(settleTolerance) / zeta;
  const omegaD = omega * Math.sqrt(1 - zeta * zeta);
  const points: [number, number][] = [];
  for (let i = 0; i <= samples; i++) {
    const t = i / samples;
    const envelope = Math.exp(-zeta * omega * t);
    const x =
      1 -
      envelope *
        (Math.cos(omegaD * t) + (zeta / Math.sqrt(1 - zeta * zeta)) * Math.sin(omegaD * t));
    points.push([t, i === samples ? 1 : x]);
  }
  return points;
}

/** Drops points that linear interpolation between their neighbours reproduces within tolerance. */
export function simplify(points: [number, number][], tolerance: number): [number, number][] {
  if (points.length <= 2) return points;
  const kept: [number, number][] = [points[0]!];
  let anchor = 0;
  for (let i = 2; i < points.length; i++) {
    const [t0, x0] = points[anchor]!;
    const [t1, x1] = points[i]!;
    const withinTolerance = points.slice(anchor + 1, i).every(([t, x]) => {
      const expected = x0 + ((x1 - x0) * (t - t0)) / (t1 - t0);
      return Math.abs(expected - x) <= tolerance;
    });
    if (!withinTolerance) {
      kept.push(points[i - 1]!);
      anchor = i - 1;
    }
  }
  kept.push(points[points.length - 1]!);
  return kept;
}

export function toLinear(points: [number, number][]): string {
  const stops = points.map(([t, x], i) => {
    const value = Number(x.toFixed(4));
    if (i === 0 || i === points.length - 1) return String(value);
    return `${value} ${Number((t * 100).toFixed(2))}%`;
  });
  return `linear(${stops.join(', ')})`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const points = simplify(
    springCurve({ damping: 0.45, settleTolerance: 0.002, samples: 240, simplifyTolerance: 0.004 }),
    0.004,
  );
  const css = `/* Generated by tools/design/spring.ts. Do not edit by hand. */

:root {
  /* A damped spring: swings about 20% past north, back 4%, then settles. ${points.length} stops. */
  --ease-settle: ${toLinear(points)};
}

@supports not (transition-timing-function: linear(0, 1)) {
  :root {
    --ease-settle: cubic-bezier(0.34, 1.56, 0.64, 1);
  }
}
`;
  const target = path.join(ROOT, 'src/styles/easing.css');
  await writeFile(target, css);
  console.error(`[design] Wrote ${path.relative(ROOT, target)} (${points.length} stops)`);
}
